// tn-stage2022-react/src/components/MessageBlock/MessageBlock.tsx
import { IonButton, IonItem, IonLabel } from '@ionic/react';
import { FC } from 'react';
import { Message } from '../../interfaces/Message';
import './MessageBlock.module.css';

interface MessageBlockProps {
  message: Message,
  deleteHandler: Function
}

const MessageBlock: FC<MessageBlockProps> = ({ message, deleteHandler }) => {
  const deleteMessage = () => {
    console.log('Emitting delete message for', message.id)
    deleteHandler(message.id)
  }

  return <IonItem lines="full">
      <IonLabel>
        <div>
          <h2>{message.title}</h2>
          <span>From: </span>
          <span className="email">{message.from}</span>
          <span> to: </span>
          <span className="email">{message.to}</span>
          <p>{message.description}</p>
        </div>
      </IonLabel>
      <IonButton size="large" onClick={deleteMessage}>
        <span>Delete</span>
      </IonButton>
    </IonItem>
}

export default MessageBlock;

// tn-stage2022-vue/src/components/MessageBlock.vue
<template>
  <ion-item lines="full">
    <ion-label>
      <div>
        <h2>{{ message.title }}</h2>
        <span>From: </span>
        <span class="email">{{ message.from }}</span>
        <span> to: </span>
        <span class="email">{{ message.to }}</span>
        <p>{{ message.description }}</p>
      </div>
    </ion-label>
    <ion-button size="large" @click="deleteMessage()">
      <span>Delete</span>
    </ion-button>
  </ion-item>
</template>

<script>
import { useStore } from '@/store';
import { IonButton, IonItem, IonLabel } from '@ionic/vue';

export default {
  components: {
    IonItem,
    IonLabel,
    IonButton
  },
  props: {
    message: {
      required: true,
      type: Object
    }
  },
  setup() {
    const store = useStore()

    return { store }
  },
  methods: {
    deleteMessage() {
      console.log('Emitting delete message for', this.message.id)
      const id = this.message.id

      this.store.deleteMessage(id)
    }
  }
}
</script>

<style lang="css" scoped>
.email {
  font-family: Helvetica, sans-serif;
  font-style: italic;
  color: #444;
}
</style>
